# Generated by Django 3.2.5 on 2022-02-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220206_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='audiofile',
        ),
        migrations.RemoveField(
            model_name='video',
            name='videofile',
        ),
        migrations.AddField(
            model_name='video',
            name='audio',
            field=models.FileField(null=True, upload_to='audios', verbose_name=''),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='videos', verbose_name=''),
        ),
    ]
