# Generated by Django 3.2.5 on 2022-02-07 11:04

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220207_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='out',
            field=models.FileField(null=True, upload_to=app.models.content_file_name_out, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='audio',
            field=models.FileField(null=True, upload_to=app.models.content_file_name, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='topic',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to=app.models.content_file_name, verbose_name=''),
        ),
    ]
