# Generated by Django 3.2.5 on 2022-02-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220207_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='out',
        ),
    ]
